test fuerther

diff --git a/.github/workflows/second-action.yml b/.github/workflows/second-action.yml
--- a/.github/workflows/second-action.yml
+++ b/.github/workflows/second-action.yml
@@ -16,9 +16,25 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: bicep-artifacts
-          # run-id: ${{ github.event.workflow_run.id }}
-          # github-token: ${{ secrets.GITHUB_TOKEN }}
+          run-id: ${{ github.event.workflow_run.id }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Show downloaded artifacts
         run: |
           dir
+
+      - name: Read Bicep File Name and Directory
+        run: |
+            echo "BICEP_FILE_NAME=$(cat bicepFileName.txt)" >> $GITHUB_ENV
+            echo "BICEP_DIRECTORY=$(cat bicepDirectory.txt)" >> $GITHUB_ENV
+
+      - name: Determine specific Documentation Directory location
+        run: |
+              # Extract the ./doc/Bicep/ directory name (eg: atomic, composite, service, type) from the $BICEP_DIRECTORY variable
+              if ($env:BICEP_DIRECTORY -match "src/main/bicep/(.*)") {
+                $DOC_FOLDER = $matches[1]
+                echo "DOC_FOLDER=$DOC_FOLDER" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
+              } else {
+                Write-Error "Failed to determine doc output folder from $env:BICEP_DIRECTORY"
+                exit 1
+              }
